package forms;

import beans.Kontrahent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KontrahentGui.java
 *
 * Created on 2011-04-10, 20:10:59
 */
/**
 *
 * @author Mariusz
 */
public class KontrahentGui extends javax.swing.JDialog {

    private int idpress;

    /** Creates new form KontrahentGui */
    public KontrahentGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ListaKontrahentow();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldSkrot = new javax.swing.JTextField();
        jTextFieldNazwa = new javax.swing.JTextField();
        jTextFieldMiejscowosc = new javax.swing.JTextField();
        jTextFieldKod = new javax.swing.JTextField();
        jTextFieldUlica = new javax.swing.JTextField();
        jTextFieldNip = new javax.swing.JTextField();
        jTextFieldKonto = new javax.swing.JTextField();
        jTextFieldTel = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldOsoba = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Nowy = new javax.swing.JButton();
        Zapisz = new javax.swing.JButton();
        Usun = new javax.swing.JButton();
        Zamknij = new javax.swing.JButton();
        Edytuj = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kontrahenci");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextFieldSkrot.setEditable(false);

        jTextFieldNazwa.setEditable(false);

        jTextFieldMiejscowosc.setEditable(false);

        jTextFieldKod.setEditable(false);

        jTextFieldUlica.setEditable(false);

        jTextFieldNip.setEditable(false);

        jTextFieldKonto.setEditable(false);

        jTextFieldTel.setEditable(false);

        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });

        jTextFieldOsoba.setEditable(false);

        jLabel1.setText("Skrót");

        jLabel2.setText("Nazwa");

        jLabel3.setText("Miasto");

        jLabel4.setText("Kod pocztowy");

        jLabel5.setText("Ulica i nr");

        jLabel6.setText("NIP");

        jLabel7.setText("Nr Konta");

        jLabel8.setText("Telefon");

        jLabel9.setText("e-mail");

        jLabel10.setText("Osoba do faktur");

        Nowy.setText("Nowy");
        Nowy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Nowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NowyActionPerformed(evt);
            }
        });

        Zapisz.setText("Zapisz");
        Zapisz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZapiszActionPerformed(evt);
            }
        });

        Usun.setText("Usuń");
        Usun.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Usun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunActionPerformed(evt);
            }
        });

        Zamknij.setText("Zamknij");
        Zamknij.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZamknijActionPerformed(evt);
            }
        });

        Edytuj.setText("Edytuj");
        Edytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdytujActionPerformed(evt);
            }
        });

        jButton1.setText("Raport");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldSkrot, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(jTextFieldNazwa)
                                .addComponent(jTextFieldMiejscowosc)
                                .addComponent(jTextFieldKod)
                                .addComponent(jTextFieldUlica)
                                .addComponent(jTextFieldNip)
                                .addComponent(jTextFieldKonto)
                                .addComponent(jTextFieldTel)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addComponent(Zamknij, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(Zapisz, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(Usun, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(Edytuj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(Nowy, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSkrot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nowy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Edytuj)
                .addGap(11, 11, 11)
                .addComponent(Usun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Zapisz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Zamknij)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZapiszActionPerformed

        Kontrahent objKontrahent = new Kontrahent();
        objKontrahent.setSkrot(this.jTextFieldSkrot.getText());
        objKontrahent.setNazwa(this.jTextFieldNazwa.getText());
        objKontrahent.setNip(this.jTextFieldNip.getText());
        objKontrahent.setKod(this.jTextFieldKod.getText());
        objKontrahent.setMiasto(this.jTextFieldMiejscowosc.getText());
        objKontrahent.setUlica(this.jTextFieldUlica.getText());
        objKontrahent.setKonto(this.jTextFieldKonto.getText());
        objKontrahent.setOsoba(this.jTextFieldOsoba.getText());
        objKontrahent.setTel(this.jTextFieldTel.getText());
        objKontrahent.setEmail(this.jTextFieldEmail.getText());
        if (idpress == 0) {
            objKontrahent.dodajKontrahenta();
        } else {
            objKontrahent.poprawKontrahenta(idpress);
        }
        ListaKontrahentow();
    }//GEN-LAST:event_ZapiszActionPerformed

    private void UsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunActionPerformed
        int usun = JOptionPane.showConfirmDialog(null, "Czy na pewno usunąc kontrahenta?");
        if (usun == 0) {
            Kontrahent objKontrahent = new Kontrahent();
            objKontrahent.setId(idpress);
            objKontrahent.usunKontrahenta();
            ListaKontrahentow();
        }
    }//GEN-LAST:event_UsunActionPerformed

    private void EdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdytujActionPerformed

        jTextEditable(true);
        this.Nowy.setEnabled(false);
        this.Edytuj.setEnabled(false);
        this.Usun.setEnabled(false);
        this.Zapisz.setEnabled(true);

    }//GEN-LAST:event_EdytujActionPerformed

    private void ZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZamknijActionPerformed
        this.dispose();
    }//GEN-LAST:event_ZamknijActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        this.Nowy.setEnabled(true);
        this.Edytuj.setEnabled(true);
        this.Usun.setEnabled(true);
        this.Zapisz.setEnabled(false);
        int rec = this.jTable1.getSelectedRow();
        idpress = Integer.parseInt(jTable1.getValueAt(rec, 0).toString());

        Kontrahent objKontrahent = new Kontrahent();
        objKontrahent.znajdzKontrahenta(idpress);

        this.jTextFieldSkrot.setText(objKontrahent.getSkrot());
        this.jTextFieldNazwa.setText(objKontrahent.getNazwa());
        this.jTextFieldMiejscowosc.setText(objKontrahent.getMiasto());
        this.jTextFieldKod.setText(objKontrahent.getKod());
        this.jTextFieldUlica.setText(objKontrahent.getUlica());
        this.jTextFieldNip.setText(objKontrahent.getNip());
        this.jTextFieldKonto.setText(objKontrahent.getKonto());
        this.jTextFieldTel.setText(objKontrahent.getTel());
        this.jTextFieldEmail.setText(objKontrahent.getEmail());
        this.jTextFieldOsoba.setText(objKontrahent.getOsoba());

        jTextEditable(false);

    }//GEN-LAST:event_jTable1MousePressed

    private void NowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NowyActionPerformed

        idpress = 0;
        jTextEditable(true);
        this.jTextFieldSkrot.setText(null);
        this.jTextFieldNazwa.setText(null);
        this.jTextFieldMiejscowosc.setText(null);
        this.jTextFieldKod.setText(null);
        this.jTextFieldUlica.setText(null);
        this.jTextFieldNip.setText(null);
        this.jTextFieldKonto.setText(null);
        this.jTextFieldTel.setText(null);
        this.jTextFieldEmail.setText(null);
        this.jTextFieldOsoba.setText(null);
        this.Nowy.setEnabled(false);
        this.Edytuj.setEnabled(false);
        this.Usun.setEnabled(false);
        this.Zapisz.setEnabled(true);

    }//GEN-LAST:event_NowyActionPerformed

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void ListaKontrahentow() {
        DefaultTableModel table = new DefaultTableModel();
        Kontrahent objKontrahent = new Kontrahent();
        ArrayList<Kontrahent> listaKontrahentow = new ArrayList();
        listaKontrahentow = objKontrahent.ListaKontrahentów();

        table.addColumn("id");
        table.addColumn("Skrót");
        table.addColumn("Nazwa");
        table.addColumn("NIP");
        table.setRowCount(listaKontrahentow.size());
        int i = 0;
        //System.out.println("lista size = " + lista3.size());
        for (Kontrahent x : listaKontrahentow) {
            table.setValueAt(x.getId(), i, 0);
            table.setValueAt(x.getSkrot(), i, 1);
            table.setValueAt(x.getNazwa(), i, 2);
            table.setValueAt(x.getNip(), i, 3);
            i++;
        }
        
        this.jTable1.setModel(table);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        jTextEditable(false);

        this.Nowy.setEnabled(true);
        this.Edytuj.setEnabled(false);
        this.Usun.setEnabled(false);
        this.Zapisz.setEnabled(false);

        this.jTextFieldSkrot.setText(null);
        this.jTextFieldNazwa.setText(null);
        this.jTextFieldMiejscowosc.setText(null);
        this.jTextFieldKod.setText(null);
        this.jTextFieldUlica.setText(null);
        this.jTextFieldNip.setText(null);
        this.jTextFieldKonto.setText(null);
        this.jTextFieldTel.setText(null);
        this.jTextFieldEmail.setText(null);
        this.jTextFieldOsoba.setText(null);

    }

    public void jTextEditable(boolean a) {

        if (a) {
            this.jTextFieldSkrot.setEditable(true);
            this.jTextFieldNazwa.setEditable(true);
            this.jTextFieldMiejscowosc.setEditable(true);
            this.jTextFieldKod.setEditable(true);
            this.jTextFieldUlica.setEditable(true);
            this.jTextFieldNip.setEditable(true);
            this.jTextFieldKonto.setEditable(true);
            this.jTextFieldTel.setEditable(true);
            this.jTextFieldEmail.setEditable(true);
            this.jTextFieldOsoba.setEditable(true);
        } else {
            this.jTextFieldSkrot.setEditable(false);
            this.jTextFieldNazwa.setEditable(false);
            this.jTextFieldMiejscowosc.setEditable(false);
            this.jTextFieldKod.setEditable(false);
            this.jTextFieldUlica.setEditable(false);
            this.jTextFieldNip.setEditable(false);
            this.jTextFieldKonto.setEditable(false);
            this.jTextFieldTel.setEditable(false);
            this.jTextFieldEmail.setEditable(false);
            this.jTextFieldOsoba.setEditable(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                KontrahentGui dialog = new KontrahentGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edytuj;
    private javax.swing.JButton Nowy;
    private javax.swing.JButton Usun;
    private javax.swing.JButton Zamknij;
    private javax.swing.JButton Zapisz;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldKod;
    private javax.swing.JTextField jTextFieldKonto;
    private javax.swing.JTextField jTextFieldMiejscowosc;
    private javax.swing.JTextField jTextFieldNazwa;
    private javax.swing.JTextField jTextFieldNip;
    private javax.swing.JTextField jTextFieldOsoba;
    private javax.swing.JTextField jTextFieldSkrot;
    private javax.swing.JTextField jTextFieldTel;
    private javax.swing.JTextField jTextFieldUlica;
    // End of variables declaration//GEN-END:variables
}
